# Generated by Django 2.2.6 on 2019-10-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_accountemailaddress_accountemailconfirmation_authtokentoken_djangosite_socialaccountsocialaccount_so'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('restname', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'trend',
                'managed': False,
            },
        ),
    ]
